name: event_app

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1 # For making HTTP requests
  shared_preferences: ^2.2.3 # For local storage of token
  provider: ^6.1.2 # For state management
  go_router: ^15.1.3 # For routing and navigation
  intl: ^0.20.2 # For date formatting
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - .env